# Generated by Django 3.0.1 on 2019-12-19 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='default_provider',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='trader.ServiceProvider'),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_rate', models.IntegerField(default=0)),
                ('default_broker', models.ForeignKey(default=None, null=True,
                                                     on_delete=django.db.models.deletion.PROTECT, related_name='+', to='trader.Broker')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
