# Generated by Django 2.2.6 on 2019-10-12 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_riskmanagementsettings_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskmanagementsettings',
            options={'verbose_name': 'Risk Managent Settings', 'verbose_name_plural': 'Risk Managent Settings'},
        ),
        migrations.AlterField(
            model_name='riskmanagementsettings',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_management_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
