# Generated by Django 3.0.1 on 2019-12-19 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_auto_20191219_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='default_provider',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trader.ServiceProvider'),
        ),
    ]
