# Generated by Django 2.2.6 on 2019-11-17 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trader', '0003_auto_20191012_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('exposure_percent', models.IntegerField()),
                ('profit_percent', models.IntegerField()),
                ('loss_percent', models.IntegerField()),
                ('fee_per_trade', models.FloatField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risk Strategy',
                'verbose_name_plural': 'Risk Strategies',
            },
        ),
    ]
