# Generated by Django 3.0.1 on 2019-12-20 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0003_auto_20191219_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='default_strategy',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='trader.TradingStrategy'),
        ),
    ]
