# Generated by Django 2.2.7 on 2019-11-22 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trader', '0005_auto_20191117_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('protocol', models.CharField(choices=[('OAUTH1', 'OAuth 1.0a'), ('OAUTH2', 'OAuth 2')], default='OAUTH1', max_length=10)),
                ('consumer_key', models.CharField(max_length=250)),
                ('consumer_secret', models.CharField(max_length=250)),
                ('request_token_url', models.CharField(blank=True, max_length=250, null=True)),
                ('authorize_url', models.CharField(blank=True, max_length=250, null=True)),
                ('access_token_url', models.CharField(blank=True, max_length=250, null=True)),
                ('refresh_url', models.CharField(blank=True, max_length=250, null=True)),
                ('revoke_url', models.CharField(blank=True, max_length=250, null=True)),
                ('base_url', models.CharField(blank=True, max_length=250, null=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_providers', to='trader.Broker')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_providers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
