# Generated by Django 3.0.1 on 2019-12-21 13:18

from django.db import migrations


def forwards(apps, schema_editor):
    Account = apps.get_model('trader', 'Account')

    for acc in Account.objects.all():
        acc.provider = acc.broker.service_providers.first()
        acc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0005_auto_20191221_1316'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
