# Generated by Django 2.2.7 on 2019-11-22 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0006_serviceprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Requesting Access'), (1, 'Access Granted'), (2, 'Access Token Inactive'), (3, 'Access Token Expired'), (4, 'Access Token Revoked')], default=0)),
                ('request_token', models.CharField(max_length=250, null=True)),
                ('request_token_secret', models.CharField(max_length=250, null=True)),
                ('access_token', models.CharField(max_length=250, null=True)),
                ('access_token_secret', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='trader.ProviderSession'),
        ),
    ]
