# Generated by Django 3.0.1 on 2019-12-21 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0006_populate_account_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='trader.ServiceProvider'),
        ),
    ]
