# Generated by Django 3.0.1 on 2019-12-26 19:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0007_auto_20191221_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingstrategy',
            name='exposure_percent',
            field=models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='tradingstrategy',
            name='loss_percent',
            field=models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='tradingstrategy',
            name='price_margin',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.01'), max_digits=5, max_length=Decimal('0.01')),
        ),
        migrations.AlterField(
            model_name='tradingstrategy',
            name='profit_percent',
            field=models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
