# Generated by Django 2.2.7 on 2019-12-01 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trader', '0007_auto_20191122_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('exposure_percent', models.IntegerField()),
                ('profit_percent', models.IntegerField()),
                ('loss_percent', models.IntegerField()),
                ('fee_per_trade', models.DecimalField(
                    decimal_places=2, default=0, max_digits=5)),
                ('price_margin', models.DecimalField(
                    decimal_places=2, default=2, max_digits=5)),
                ('max_price_margin', models.DecimalField(
                    decimal_places=2, default=0.02, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='trading_strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trading Strategy',
                'verbose_name_plural': 'Trading Strategies',
            },
        ),
        migrations.RemoveField(
            model_name='account',
            name='number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='purchasing_power',
        ),
        migrations.AddField(
            model_name='account',
            name='account_id',
            field=models.CharField(
                default='one-off-default-for-migration', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='account_key',
            field=models.CharField(
                default='one-off-default-for-migration', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='account_mode',
            field=models.CharField(
                choices=[('CASH', 'CASH'), ('MARGIN', 'MARGIN')], default='CASH', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='account_status',
            field=models.CharField(choices=[(
                'ACTIVE', 'ACTIVE'), ('CLOSED', 'CLOSED')], default='ACTIVE', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(default='BROKERAGE', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='cash_balance',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='cash_buying_power',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(default='DESC', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='institution_type',
            field=models.CharField(default='institution', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='margin_buying_power',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='pdt_status',
            field=models.CharField(default='pdt-status', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='accounts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='broker',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='brokers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='service_providers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RiskStrategy',
        ),
    ]
