# Generated by Django 2.2.7 on 2019-12-03 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trader', '0008_auto_20191201_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='slug',
            field=models.SlugField(default='broker-url', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='slug',
            field=models.SlugField(default='provider-url', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='broker',
            unique_together={('user', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='serviceprovider',
            unique_together={('broker', 'slug')},
        ),
    ]
