# Generated by Django 3.0.3 on 2020-02-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0009_autopilottask'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopilottask',
            name='tracking_order_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
