# Generated by Django 3.0.3 on 2020-02-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0011_autopilottask_is_otc'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopilottask',
            name='error_message',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='autopilottask',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Buying Mode'), (1, 'Watching Mode'), (2, 'Selling Mode'), (3, 'Error Mode')], default=1),
        ),
    ]
