# Generated by Django 3.0.3 on 2020-02-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0013_auto_20200222_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autopilottask',
            old_name='ref_price',
            new_name='profit_ref_price',
        ),
        migrations.AddField(
            model_name='autopilottask',
            name='loss_ref_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autopilottask',
            name='modifier',
            field=models.SmallIntegerField(choices=[(0, 'Follow Strategy'), (1, 'Maximize Profit'), (2, 'Minimize Loss'), (3, 'Minimize Loss, Maximize Profit')], default=0),
        ),
    ]
