# Generated by Django 3.0.3 on 2020-02-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0014_auto_20200226_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='default_autopilot_modifier',
            field=models.SmallIntegerField(choices=[(0, 'Follow Strategy'), (1, 'Maximize Profit'), (2, 'Minimize Loss'), (3, 'Minimize Loss, Maximize Profit')], default=0),
        ),
    ]
