# Generated by Django 3.0.3 on 2020-03-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0015_settings_default_autopilot_modifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cash_available_for_investment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='net_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
