# Generated by Django 3.0.3 on 2020-03-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0018_account_total_account_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='discord_webhook',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
