# Generated by Django 3.0.3 on 2020-03-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0019_settings_discord_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopilottask',
            name='discord_webhook',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
