# Generated by Django 3.0.4 on 2020-03-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0022_autopilottask_tracking_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopilottask',
            name='base_price',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='autopilottask',
            name='entry_price',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='autopilottask',
            name='loss_ref_price',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='autopilottask',
            name='profit_ref_price',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
