# Generated by Django 3.0.4 on 2020-03-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0023_auto_20200318_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopilottask',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12),
        ),
    ]
